//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mmsdbEntities : DbContext
    {
        public mmsdbEntities()
            : base("name=mmsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MMS_Beobachter> MMS_Beobachter { get; set; }
        public virtual DbSet<MMS_Beobachtertouren> MMS_Beobachtertouren { get; set; }
        public virtual DbSet<MMS_Bereich> MMS_Bereich { get; set; }
        public virtual DbSet<MMS_Maschinenbeobachtung> MMS_Maschinenbeobachtung { get; set; }
        public virtual DbSet<MMS_Maschinenzustand> MMS_Maschinenzustand { get; set; }
        public virtual DbSet<MMS_Mitarbeiter> MMS_Mitarbeiter { get; set; }
        public virtual DbSet<MMS_Mitarbeiterbeobachtung> MMS_Mitarbeiterbeobachtung { get; set; }
        public virtual DbSet<MMS_Mitarbeiterfunktion> MMS_Mitarbeiterfunktion { get; set; }
        public virtual DbSet<MMS_Obertaetigkeit_Untertaetigkeit> MMS_Obertaetigkeit_Untertaetigkeit { get; set; }
        public virtual DbSet<MMS_Ort> MMS_Ort { get; set; }
        public virtual DbSet<MMS_Taetigkeit> MMS_Taetigkeit { get; set; }
        public virtual DbSet<MMS_Tourinformation> MMS_Tourinformation { get; set; }
    }
}
