//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Obertaetigkeit_Untertaetigkeit
    {
        public int Obertaetigkeit { get; set; }
        public int Untertaetigkeit { get; set; }
    
        public virtual MMS_Taetigkeit MMS_Taetigkeit { get; set; }
    }
}
