//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Maschinenbeobachtung
    {
        public int Beobachter_ID { get; set; }
        public System.DateTime Datum { get; set; }
        public int Maschinenort_ID { get; set; }
        public Nullable<int> Maschinenzustand_ID { get; set; }
    
        public virtual MMS_Maschinenbeobachtung MMS_Maschinenbeobachtung1 { get; set; }
        public virtual MMS_Maschinenbeobachtung MMS_Maschinenbeobachtung2 { get; set; }
    }
}
