//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Beobachtertouren
    {
        public int Beobachter_ID { get; set; }
        public int Bereich_ID { get; set; }
        public string Tourart { get; set; }
        public System.DateTime Datum { get; set; }
        public string Tourreihenfolge { get; set; }
        public string Mitarbeiterliste { get; set; }
    
        public virtual MMS_Beobachter MMS_Beobachter { get; set; }
        public virtual MMS_Bereich MMS_Bereich { get; set; }
    }
}
