//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Mitarbeiter
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public Nullable<int> Funktion_ID { get; set; }
        public string Bereich { get; set; }
    
        public virtual MMS_Mitarbeiter MMS_Mitarbeiter1 { get; set; }
        public virtual MMS_Mitarbeiter MMS_Mitarbeiter2 { get; set; }
    }
}
