//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Ort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MMS_Ort()
        {
            this.MMS_Mitarbeiterbeobachtung = new HashSet<MMS_Mitarbeiterbeobachtung>();
            this.MMS_Ort1 = new HashSet<MMS_Ort>();
            this.MMS_Ort2 = new HashSet<MMS_Ort>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Bereich_ID { get; set; }
        public string Bezeichnung { get; set; }
        public string Typ { get; set; }
    
        public virtual MMS_Bereich MMS_Bereich { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Mitarbeiterbeobachtung> MMS_Mitarbeiterbeobachtung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Ort> MMS_Ort1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Ort> MMS_Ort2 { get; set; }
    }
}
