//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularTest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMS_Taetigkeit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MMS_Taetigkeit()
        {
            this.MMS_Mitarbeiterbeobachtung = new HashSet<MMS_Mitarbeiterbeobachtung>();
            this.MMS_Obertaetigkeit_Untertaetigkeit = new HashSet<MMS_Obertaetigkeit_Untertaetigkeit>();
        }
    
        public int ID { get; set; }
        public string Taetigkeit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Mitarbeiterbeobachtung> MMS_Mitarbeiterbeobachtung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMS_Obertaetigkeit_Untertaetigkeit> MMS_Obertaetigkeit_Untertaetigkeit { get; set; }
    }
}
